### ISSUE TITLE
Worker couldn't process data after upgrade

### ISSUE THREAD

**Issue by chiefmc** [getsentry/self-hosted#1657]
### Self-Hosted Version

22.8.0

### CPU Architecture

x86_64

### Docker Version

19.03.15

### Docker Compose Version

1.29.2

### Steps to Reproduce

After upgrade to version 21.12.0 (and subsequently to 22.8.0) we've stop getting new events into the system.

Install was made as per docs, with `./install.sh` launch.

During the install script I have the following error, which I haven't been able to resolve:
```
16:13:38 [INFO] sentry.plugins.github: apps-not-configured
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/redis.py", line 123, in setup_once
    _patch_rediscluster()
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/redis.py", line 88, in _patch_rediscluster
    pipeline_cls = rediscluster.ClusterPipeline
AttributeError: module 'rediscluster' has no attribute 'ClusterPipeline'
16:13:38 [ERROR] sentry_sdk.errors: Error occurred while patching `rediscluster` library
```
The rest seems to be fine.

After the start-up of all the services old events couldn't be opened and new ones are not getting through:
> Sorry, the events for this issue could not be found.
> 
> This could be due to a handful of reasons:
> 
>     The events are still processing and are on their way
>     The events have been deleted
>     There is an internal systems error or active issue

The only obvious error I see in worker log is repetitive:
```
worker_1                                    | 15:40:18 [ERROR] celery.app.trace: Task sentry.tasks.store.save_event[7e947fef-75cc-40ac-afda-2f8e4b5bc1de] raised unexpected: KafkaException('KafkaError{code=_INVALID_ARG,val=-186,str="No such configuration property: "log.retention.bytes""}') (data={'hostname': 'e05102e61639', 'id': '7e947fef-75cc-40ac-afda-2f8e4b5bc1de', 'name': 'sentry.tasks.store.save_event', 'exc': 'KafkaException(\'KafkaError{code=_INVALID_ARG,val=-186,str="No such configuration property: "log.retention.bytes""}\')', 'traceback': 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task\n    R = retval = fun(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 204, in _inner\n    reraise(*exc_info)\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 54, in reraise\n    raise value\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 199, in _inner\n    return f(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__\n    return self.run(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/base.py", line 64, in _wrapped\n    result = func(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/store.py", line 798, in save_event\n    _do_save_event(cache_key, data, start_time, event_id, project_id, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/store.py", line 691, in _do_save_event\n    manager.save(\n  File "/usr/local/lib/python3.8/site-packages/sentry/utils/metrics.py", line 250, in inner\n    return f(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/event_manager.py", line 565, in save\n    _eventstream_insert_many(jobs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/utils/metrics.py", line 250, in inner\n    return f(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/event_manager.py", line 985, in _eventstream_insert_many\n    eventstream.insert(\n  File "/usr/local/lib/python3.8/site-packages/sentry/utils/services.py", line 127, in <lambda>\n    context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)\n  File "/usr/local/lib/python3.8/site-packages/sentry/eventstream/kafka/backend.py", line 133, in insert\n    return super().insert(\n  File "/usr/local/lib/python3.8/site-packages/sentry/eventstream/snuba.py", line 141, in insert\n    self._send(\n  File "/usr/local/lib/python3.8/site-packages/sentry/eventstream/kafka/backend.py", line 170, in _send\n    self.producer.poll(0.0)\n  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 80, in __get__\n    res = instance.__dict__[self.name] = self.func(instance)\n  File "/usr/local/lib/python3.8/site-packages/sentry/eventstream/kafka/backend.py", line 40, in producer\n    return kafka.producers.get(settings.KAFKA_EVENTS)\n  File "/usr/local/lib/python3.8/site-packages/sentry/utils/kafka.py", line 34, in get\n    producer = self.__producers[cluster_name] = Producer(cluster_options)\ncimpl.KafkaException: KafkaError{code=_INVALID_ARG,val=-186,str="No such configuration property: "log.retention.bytes""}\n', 'args': '()', 'kwargs': "{'cache_key': 'e:2169d2b37b19413cbf1399dd75c00066:1', 'data': None, 'start_time': 1660836991.0, 'event_id': '2169d2b37b19413cbf1399dd75c00066', 'project_id': 1}", 'description': 'raised unexpected', 'internal': False})
worker_1                                    | 15:40:18 [ERROR] sentry_sdk.errors: Unexpected status code: 521 (body: b'')
worker_1                                    | Traceback (most recent call last):
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/billiard/pool.py", line 366, in workloop
worker_1                                    |     put((READY, (job, i, result, inqW_fd)))
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/billiard/queues.py", line 366, in put
worker_1                                    |     self.send_payload(ForkingPickler.dumps(obj))
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/billiard/reduction.py", line 56, in dumps
worker_1                                    |     cls(buf, protocol).dump(obj)
worker_1                                    | billiard.pool.MaybeEncodingError: Error sending result: ''(1, <ExceptionInfo: KafkaException(\'KafkaError{code=_INVALID_ARG,val=-186,str="No such configuration property: "log.retention.bytes""}\')>, None)''. Reason: ''PicklingError("Can\'t pickle <class \'cimpl.KafkaException\'>: import of module \'cimpl\' failed")''.
worker_1                                    | 15:40:18 [ERROR] celery.worker.request: Task handler raised error: <MaybeEncodingError: Error sending result: ''(1, <ExceptionInfo: KafkaException(\'KafkaError{code=_INVALID_ARG,val=-186,str="No such configuration property: "log.retention.bytes""}\')>, None)''. Reason: ''PicklingError("Can\'t pickle <class \'cimpl.KafkaException\'>: import of module \'cimpl\' failed")''.>
worker_1                                    | 15:40:18 [ERROR] sentry_sdk.errors: Unexpected status code: 521 (body: b'')
worker_1                                    | 15:40:18 [ERROR] sentry_sdk.errors: Unexpected status code: 521 (body: b'')
worker_1                                    | Traceback (most recent call last):
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/billiard/pool.py", line 366, in workloop
worker_1                                    |     put((READY, (job, i, result, inqW_fd)))
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/billiard/queues.py", line 366, in put
worker_1                                    |     self.send_payload(ForkingPickler.dumps(obj))
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/billiard/reduction.py", line 56, in dumps
worker_1                                    |     cls(buf, protocol).dump(obj)
worker_1                                    | billiard.pool.MaybeEncodingError: Error sending result: ''(1, <ExceptionInfo: KafkaException(\'KafkaError{code=_INVALID_ARG,val=-186,str="No such configuration property: "log.retention.bytes""}\')>, None)''. Reason: ''PicklingError("Can\'t pickle <class \'cimpl.KafkaException\'>: import of module \'cimpl\' failed")''.
worker_1                                    | 15:40:18 [ERROR] celery.worker.request: Task handler raised error: <MaybeEncodingError: Error sending result: ''(1, <ExceptionInfo: KafkaException(\'KafkaError{code=_INVALID_ARG,val=-186,str="No such configuration property: "log.retention.bytes""}\')>, None)''. Reason: ''PicklingError("Can\'t pickle <class \'cimpl.KafkaException\'>: import of module \'cimpl\' failed")''.>
worker_1                                    | Traceback (most recent call last):
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/billiard/pool.py", line 366, in workloop
worker_1                                    |     put((READY, (job, i, result, inqW_fd)))
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/billiard/queues.py", line 366, in put
worker_1                                    |     self.send_payload(ForkingPickler.dumps(obj))
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/billiard/reduction.py", line 56, in dumps
worker_1                                    |     cls(buf, protocol).dump(obj)
worker_1                                    | billiard.pool.MaybeEncodingError: Error sending result: ''(1, <ExceptionInfo: KafkaException(\'KafkaError{code=_INVALID_ARG,val=-186,str="No such configuration property: "log.retention.bytes""}\')>, None)''. Reason: ''PicklingError("Can\'t pickle <class \'cimpl.KafkaException\'>: import of module \'cimpl\' failed")''.
worker_1                                    | 15:40:18 [ERROR] celery.worker.request: Task handler raised error: <MaybeEncodingError: Error sending result: ''(1, <ExceptionInfo: KafkaException(\'KafkaError{code=_INVALID_ARG,val=-186,str="No such configuration property: "log.retention.bytes""}\')>, None)''. Reason: ''PicklingError("Can\'t pickle <class \'cimpl.KafkaException\'>: import of module \'cimpl\' failed")''.>
worker_1                                    | Traceback (most recent call last):
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task
worker_1                                    |     R = retval = fun(*args, **kwargs)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 204, in _inner
worker_1                                    |     reraise(*exc_info)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 54, in reraise
worker_1                                    |     raise value
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 199, in _inner
worker_1                                    |     return f(*args, **kwargs)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__
worker_1                                    |     return self.run(*args, **kwargs)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry/tasks/base.py", line 64, in _wrapped
worker_1                                    |     result = func(*args, **kwargs)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry/tasks/store.py", line 798, in save_event
worker_1                                    |     _do_save_event(cache_key, data, start_time, event_id, project_id, **kwargs)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry/tasks/store.py", line 691, in _do_save_event
worker_1                                    |     manager.save(
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry/utils/metrics.py", line 250, in inner
worker_1                                    |     return f(*args, **kwargs)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry/event_manager.py", line 565, in save
worker_1                                    |     _eventstream_insert_many(jobs)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry/utils/metrics.py", line 250, in inner
worker_1                                    |     return f(*args, **kwargs)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry/event_manager.py", line 985, in _eventstream_insert_many
worker_1                                    |     eventstream.insert(
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry/utils/services.py", line 127, in <lambda>
worker_1                                    |     context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry/eventstream/kafka/backend.py", line 133, in insert
worker_1                                    |     return super().insert(
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry/eventstream/snuba.py", line 141, in insert
worker_1                                    |     self._send(
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry/eventstream/kafka/backend.py", line 170, in _send
worker_1                                    |     self.producer.poll(0.0)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 80, in __get__
worker_1                                    |     res = instance.__dict__[self.name] = self.func(instance)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry/eventstream/kafka/backend.py", line 40, in producer
worker_1                                    |     return kafka.producers.get(settings.KAFKA_EVENTS)
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry/utils/kafka.py", line 34, in get
worker_1                                    |     producer = self.__producers[cluster_name] = Producer(cluster_options)
worker_1                                    | cimpl.KafkaException: KafkaError{code=_INVALID_ARG,val=-186,str="No such configuration property: "log.retention.bytes""}
```
Despite the error says: `KafkaException(\'KafkaError{code=_INVALID_ARG,val=-186,str="No such configuration property: "log.retention.bytes"` I do have the variable set in `sentry/sentry.conf.py`:
```
DEFAULT_KAFKA_OPTIONS = {
    "bootstrap.servers": "kafka:9092",
    "message.max.bytes": 50000000,
    "socket.timeout.ms": 1000,
    "log.retention.bytes": "4000000000",
    "log.retention.hours": "72",
}
```
and in `docker-compose.yml` I have:
```
      KAFKA_LOG_RETENTION_HOURS: "24"
      KAFKA_LOG_RETENTION_BYTES: "53687091200"
      KAFKA_LOG_SEGMENT_BYTES: "1073741824"
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: "300000"
      KAFKA_LOG_SEGMENT_DELETE_DELAY_MS: "60000"

```

Apart from above, I see a stream of local events from Sentry itself, which is 20x the size of the "real" events:
`xx.xx.xx.xx - - [18/Aug/2022:18:39:00 +0300] "POST /api/1/store/ HTTP/2.0" 200 174 "-" "sentry.python/1.9.4"`
Where `xx.xx.xx.xx` is the external ip of the Sentry machine.

Seems I'm stuck resolving this. Any help will be much appreciated.

### Expected Result

Should work normally, ingest and display events

### Actual Result

No new events ingested and old ones couldn't be displayed with error:
> Sorry, the events for this issue could not be found.
> 
> This could be due to a handful of reasons:
> 
>     The events are still processing and are on their way
>     The events have been deleted
>     There is an internal systems error or active issue

**Comment by ethanhs** [comment]
Hi, the error is saying that kafka does not have the option `log.retention.bytes`, perhaps you meant `log.retention.size`? Also just to make sure, that setting should go in `sentry.conf.py, not `config.yml`.

**Comment by chiefmc** [comment]
Hi! Thanks for your response.

> the error is saying that kafka does not have the option log.retention.bytes, perhaps you meant log.retention.size
Its just a copy-paste, it says exactly `log.retention.bytes`, haven't seen anywhere in docs option `log.retention.size`

> just to make sure, that setting should go in sentry.conf.py, not config.yml`
I'll give it a try. Thanks!

**Comment by chiefmc** [comment]
Also, maybe it will be helpful to know. Worker starts up and looks normally up to the point I let events through (apart from that Redis error, which I also can't get rid of):
```
root@sentry:/opt/sentry# docker-compose logs -f worker
Attaching to sentry-self-hosted_worker_1
worker_1                                    | Updating certificates in /etc/ssl/certs...
worker_1                                    | 0 added, 0 removed; done.
worker_1                                    | Running hooks in /etc/ca-certificates/update.d...
worker_1                                    | done.
worker_1                                    | 22:21:30 [INFO] sentry.plugins.github: apps-not-configured
worker_1                                    | Traceback (most recent call last):
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/redis.py", line 123, in setup_once
worker_1                                    |     _patch_rediscluster()
worker_1                                    |   File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/redis.py", line 88, in _patch_rediscluster
worker_1                                    |     pipeline_cls = rediscluster.ClusterPipeline
worker_1                                    | AttributeError: module 'rediscluster' has no attribute 'ClusterPipeline'
worker_1                                    | 22:21:31 [ERROR] sentry_sdk.errors: Error occurred while patching `rediscluster` library
worker_1                                    | 22:21:31 [INFO] sentry.bgtasks: bgtask.spawn (task_name='sentry.bgtasks.clean_dsymcache:clean_dsymcache')
worker_1                                    | 22:21:31 [INFO] sentry.bgtasks: bgtask.spawn (task_name='sentry.bgtasks.clean_releasefilecache:clean_releasefilecache')
worker_1                                    |
worker_1                                    |  -------------- celery@5f853c2bf98f v4.4.7 (cliffs)
worker_1                                    | --- ***** -----
worker_1                                    | -- ******* ---- Linux-4.9.0-19-amd64-x86_64-with-glibc2.2.5 2022-08-18 22:21:33
worker_1                                    | - *** --- * ---
worker_1                                    | - ** ---------- [config]
worker_1                                    | - ** ---------- .> app:         sentry:0x7f475213eb80
worker_1                                    | - ** ---------- .> transport:   redis://redis:6379/0
worker_1                                    | - ** ---------- .> results:     disabled://
worker_1                                    | - *** --- * --- .> concurrency: 8 (prefork)
worker_1                                    | -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
worker_1                                    | --- ***** -----
worker_1                                    |  -------------- [queues]
worker_1                                    |                 .> activity.notify  exchange=default(direct) key=activity.notify
worker_1                                    |                 .> alerts           exchange=default(direct) key=alerts
worker_1                                    |                 .> app_platform     exchange=default(direct) key=app_platform
worker_1                                    |                 .> appstoreconnect  exchange=default(direct) key=sentry.tasks.app_store_connect.#
worker_1                                    |                 .> assemble         exchange=default(direct) key=assemble
worker_1                                    |                 .> auth             exchange=default(direct) key=auth
worker_1                                    |                 .> buffers.incr     exchange=default(direct) key=buffers.incr
worker_1                                    |                 .> buffers.process_pending exchange=default(direct) key=buffers.process_pending
worker_1                                    |                 .> cleanup          exchange=default(direct) key=cleanup
worker_1                                    |                 .> code_owners      exchange=default(direct) key=code_owners
worker_1                                    |                 .> commits          exchange=default(direct) key=commits
worker_1                                    |                 .> counters-0       exchange=counters(direct) key=default
worker_1                                    |                 .> data_export      exchange=default(direct) key=data_export
worker_1                                    |                 .> default          exchange=default(direct) key=default
worker_1                                    |                 .> digests.delivery exchange=default(direct) key=digests.delivery
worker_1                                    |                 .> digests.scheduling exchange=default(direct) key=digests.scheduling
worker_1                                    |                 .> email            exchange=default(direct) key=email
worker_1                                    |                 .> events.preprocess_event exchange=default(direct) key=events.preprocess_event
worker_1                                    |                 .> events.process_event exchange=default(direct) key=events.process_event
worker_1                                    |                 .> events.reprocess_events exchange=default(direct) key=events.reprocess_events
worker_1                                    |                 .> events.reprocessing.preprocess_event exchange=default(direct) key=events.reprocessing.preprocess_event
worker_1                                    |                 .> events.reprocessing.process_event exchange=default(direct) key=events.reprocessing.process_event
worker_1                                    |                 .> events.reprocessing.symbolicate_event exchange=default(direct) key=events.reprocessing.symbolicate_event
worker_1                                    |                 .> events.reprocessing.symbolicate_event_low_priority exchange=default(direct) key=events.reprocessing.symbolicate_event_low_priority
worker_1                                    |                 .> events.save_event exchange=default(direct) key=events.save_event
worker_1                                    |                 .> events.save_event_attachments exchange=default(direct) key=events.save_event_attachments
worker_1                                    |                 .> events.save_event_transaction exchange=default(direct) key=events.save_event_transaction
worker_1                                    |                 .> events.symbolicate_event exchange=default(direct) key=events.symbolicate_event
worker_1                                    |                 .> events.symbolicate_event_low_priority exchange=default(direct) key=events.symbolicate_event_low_priority
worker_1                                    |                 .> files.delete     exchange=default(direct) key=files.delete
worker_1                                    |                 .> get_suspect_resolutions exchange=default(direct) key=get_suspect_resolutions
worker_1                                    |                 .> group_owners.process_suspect_commits exchange=default(direct) key=group_owners.process_suspect_commits
worker_1                                    |                 .> incident_snapshots exchange=default(direct) key=incident_snapshots
worker_1                                    |                 .> incidents        exchange=default(direct) key=incidents
worker_1                                    |                 .> integrations     exchange=default(direct) key=integrations
worker_1                                    |                 .> merge            exchange=default(direct) key=merge
worker_1                                    |                 .> options          exchange=default(direct) key=options
worker_1                                    |                 .> profiles.process exchange=default(direct) key=profiles.process
worker_1                                    |                 .> relay_config     exchange=default(direct) key=relay_config
worker_1                                    |                 .> relay_config_bulk exchange=default(direct) key=relay_config_bulk
worker_1                                    |                 .> release_health.duplex exchange=default(direct) key=release_health.duplex
worker_1                                    |                 .> releasemonitor   exchange=default(direct) key=releasemonitor
worker_1                                    |                 .> reports.deliver  exchange=default(direct) key=reports.deliver
worker_1                                    |                 .> reports.prepare  exchange=default(direct) key=reports.prepare
worker_1                                    |                 .> search           exchange=default(direct) key=search
worker_1                                    |                 .> sentry_metrics.indexer exchange=default(direct) key=sentry_metrics.indexer
worker_1                                    |                 .> similarity.index exchange=default(direct) key=similarity.index
worker_1                                    |                 .> sleep            exchange=default(direct) key=sleep
worker_1                                    |                 .> stats            exchange=default(direct) key=stats
worker_1                                    |                 .> subscriptions    exchange=default(direct) key=subscriptions
worker_1                                    |                 .> symbolications.compute_low_priority_projects exchange=default(direct) key=symbolications.compute_low_priority_projects
worker_1                                    |                 .> triggers-0       exchange=triggers(direct) key=default
worker_1                                    |                 .> unmerge          exchange=default(direct) key=unmerge
worker_1                                    |                 .> update           exchange=default(direct) key=update
worker_1                                    |
```

**Comment by chiefmc** [comment]
Seems that I've resolved the issue.

It started working after I've REMOVED `log.retention.bytes` and `log.retention.hours` from `sentry.conf.py`:
```
DEFAULT_KAFKA_OPTIONS = {
    "bootstrap.servers": "kafka:9092",
    "message.max.bytes": 50000000,
    "socket.timeout.ms": 1000,
}
```
